### ISSUE TITLE
Temporarily hide dialog

### ISSUE THREAD

**Issue by ray73864** [keejelo/EasyDialogBox#6] opened 2021-03-10 01:55 UTC
Is there any way to temporarily hide a dialog without officially closing it?

I have a dialog that opens up for doing one task, then on that dialog is a button to open a new dialog for a calculator, to get the calculator to show I would have to destroy the existing dialog which means losing all the information it currently has on it.

What I would like to do is hide the existing dialog so that the new one can show, then when the new one is closed, perform whatever action I need to, in this case that would be taking a value from an input on it and transferring it to an input on the original dialog.

**Comment by keejelo** [comment] 2021-03-10 08:17
Hi, the thought was to use the variable "bKeepAlive" that keeps the created dialog in memory, as a way to temporarily hide a dialog.
But I'll try to create an easier hide function.

**Comment by ray73864** [comment] 2021-03-10 08:48
Ahh, so I would set the bKeepAlive to true, and then when I destroy the dialog, I can bring it back just by doing a show?

I mean, that would work too, I just wasn't sure what bKeepAlive was about. Will it keep all the contents that are on the dialog too? Such as if I have a form that has already started being filled out?

I did manage to utilise bootstrap 5's Modals along with EasyDialogBox, but with the Bootstrap Modal open, the EasyDialog modal was inaccessible (It would show onscreen, but I couldn't access any of the form fields on it).

**Comment by keejelo** [comment] 2021-03-10 15:59
Just made a quick example of how to maybe use "bKeepAlive" and keep values when "hiding" dialog:

`<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link type="text/css" rel="stylesheet" href="css/easydlg.css" />
<script src="js/easydlg.js" charset="utf-8"></script>

<script type="text/javascript">

// ** Window load handler
window.addEventListener('load', function()
{
    // ** Create a new dialogbox object
    let myBox = EasyDialogBox.create(0, 'dlg dlg-success', 'My title','<p>Hello there!</p><p><input id="myText" type="text"></p>', 0, true);
    
    // ** Create an object variable for input box in dialog, we use it to store the value
    myBox.myText = '';
    
    // ** Create variable that will hold element reference
    DOM_myText = null;
    
    // ** onShow 
    myBox.onShow = function()
    {
        DOM_myText = document.getElementById('myText');
        
        if(DOM_myText)
        {
            DOM_myText.value = myBox.myText;
        }
    };

    // ** onClose
    myBox.onClose = function()
    {
        myBox.myText = DOM_myText.value;
    };

    
    // ** Button click handler
    var btn = document.getElementById('myBtn');
    btn.addEventListener('click', function()
    {
        myBox.show();
    });
        
});

</script>
</head>
<body>
    <button id="myBtn">Ok</button>
</body>
</html>`

**Comment by keejelo** [comment] 2021-03-10 16:11
Yes you can bring it back by doing a show, but to keep the updated form values you have to do like the example below (I just wrote down from the top of my head )
One way to use "bKeepAlive" and keep values when "hiding" dialog:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link type="text/css" rel="stylesheet" href="css/easydlg.css" />
<script src="js/easydlg.js" charset="utf-8"></script>

<script type="text/javascript">

// ** Window load handler
window.addEventListener('load', function()
{
    // ** Create a new dialogbox object
    let myBox = EasyDialogBox.create(0, 'dlg', 'My title','<p><input id="myText" type="text"></p>', 0, true);
    
    // ** Create an object variable for input box in dialog, we use it to store the value
    myBox.myTextValue = '';
    // you can create as many as you want since javascript is really just a chain of objects/variables
    
    // ** Create variable that will hold reference to element
    let DOM_myText = null;
    
    // ** onShow 
    myBox.onShow = function()
    {
        DOM_myText = document.getElementById('myText');
        
        if(DOM_myText)
        {
            DOM_myText.value = myBox.myTextValue;
        }
    };

    // ** onClose
    myBox.onClose = function()
    {
        myBox.myTextValue= DOM_myText.value;
    };

    
    // ** Button click handler
    var btn = document.getElementById('myBtn');
    btn.addEventListener('click', function()
    {
        myBox.show();
    });
        
});

</script>
</head>
<body>
    <button id="myBtn">Ok</button>
</body>
</html>
```

I think you somehow have to store your values in some temporary variables and read/write to them when showing and hiding. Not store the values in the form itself.. or you can create your forms the pre-written "HTML-way" like I describe in the documentation (bottom), and not create them dynamically with javascript, and read and write your values to the hidden form in DOM.. But I will look into maybe creating an easier way to hide dialogs.

Regarding the "bootstrap 5's Modals" I have to look into that.
(My experience with bootstrap is limited since I have never used it much.)

**Comment by keejelo** [comment] 2021-03-11 06:07
I will also try to automate so that all "form" elements (input & textbox) values will be saved on "hiding", and displayed again on "show". So that users do not have to do all that manually.
In fact I think this will be in relation to what I wrote in response to issue: #7 "Add DOM element to returned dialog"
Loop over all elements and get their value, save them to the created object, in an indexed element array.
I'll get on it.

**Comment by ray73864** [comment] 2021-03-11 06:26
Yeah, the easiest way there is if after creating the dialog in the DOM itself, put it on the returned object as for example 'el' or 'element', etc... (Bootstrap 5 does it as ```myDialog = new bootstrap.Modal()``` and then you can access the element as ```myDialog._element```.

Then, to temporarily hide the dialog, keep it in the DOM, just set it as hidden, which means it should maintain all its existing values, etc... (I think), also means that because it still exists in the DOM, and because it has been added to the returned object, it can still be accessed despite not being shown on screen.

**Comment by keejelo** [comment] 2021-03-11 06:34
Yes I think all values should be kept when dialog is hidden.
When I created this I was trying to keep a tidy DOM by not having a lot of dynamically created stuff in it, but I can see that for forms with lots of values it makes it harder to pass values back and forth. (I'm used to do it that way in other programming languages etc. where there's no other option)
I'll see if I can make it same as bootstrap does

**Comment by keejelo** [comment] 2021-03-11 08:04
btw. thank you for your interest in this project :)

**Comment by ray73864** [comment] 2021-03-11 08:38
No problem :D

I used to use bootboxjs, but when I decided to give up on jQuery because of its large filesize and slow load times, it meant I had to start looking for alternatives, and EasyDialogBox is quite honestly (with the exception of Smalltalk) the best one around.

EasyDialogBox works in IE and modern browsers, Smalltalk only works in modern browsers, but it also doesn't support custom dialog boxes.

I have been using Bootstrap 5's new stuff too, but I much prefer the feel of not having to pre-do the HTML for the dialog if I don't want to have to, as it would then mean editing the information on it before it gets displayed, at least this way I can build the dialog as I need it with the info I need it from the get-go.

**Comment by keejelo** [comment] 2021-03-13 19:20
Thanks, glad to hear that you find it useful :-) 

<strike>I've uploaded a new version for testing, something I wrote up today, didn't have time until today. 
You can check it out and see if it does what you need, if not let me know.
I've added hiding in DOM and methods to get elements inside and the dialog element itself easier.
Readme and files are in the repo here: https://github.com/keejelo/EasyDialogBox/tree/master/js/test
Try it out and post back issues etc.</strike>

Update:
New release ready with some changes.
On creation the dialog lives in DOM, keeping all values etc.

You can now hide it with the function: <code>myObj.hide();</code>

You can also get the dialog element by doing <code>myObj.el</code>

The dialog is also hidden in DOM when closing it, and it is not destroyed until the user execute the function <code>myObj.destroy();</code>

**Comment by ray73864** [comment] 2021-03-29 23:47
This is working good now, the only issue I have is that if I close the dialog via the 'X' or 'Escape', it only hides it, which leads to the DOM ending up with lots of these in it until page refresh.

Where am I supposed to call 'myObj.destroy()'? I figured in the onClose, but that didn't do anything.

**Comment by keejelo** [comment] 2021-03-30 06:02
Hi, you can do it where you want, it should work in the onClose function, at least if you set an id when you create the dialog.
I've done that  in the example: https://keejelo.github.io/EasyDialogBox/doc.html#js_example

**Comment by ray73864** [comment] 2021-03-30 06:06
Ahh ok, will have to try that then, I normally just set the id to null when I create the dialog.

**Comment by keejelo** [comment] 2021-03-30 06:08
Yeah I see, but if you set it to null it should also be possible to delete it.. (if no id is set, it will just autogenerate an id )
I need to check it out, it was working in my tests the last time I tested it...hmm..

**Comment by keejelo** [comment] 2021-03-30 15:03
I tested it now, both with using and 'id' and using just 0 (zero) or null instead of id, when creating the dialog.
Seem to destroy the dialogbox as expected when doing as the example does:
<pre>
var myBox = EasyDialogBox.create( params );

myBox.onClose = function()
{
    myBox.destroy();

    // or you can do:
    this.destroy(); 
};

// the oneliner below also seem to work to destroy box automatically when it's closed

myBox.onClose = myBox.destroy;

</pre>



..so from what I can see it is working ok ..
I'm going to test some more..

**Comment by ray73864** [comment] 2021-03-30 20:08
Just tested this again using the most recent git pull.

```
function showDialog() {
  const modal = EasyDialogBox.create(null, "dlg", "Test Dialog", html, ( returnCode, inputValue ) => { });
  modal.onClose = function() { modal.destroy(); /* Other stuff in here too */ };
  modal.show();
}

```

When the modal shows, I get a modal with id# g4mlqtrfg_0 in the DOM.
When I close the modal either via the 'x' or 'escape', it's style goes from being ```display: block``` to ```display: none```.

If I then run the ```showDialog()``` function again, I get a modal with id# wd2nx7bgj_0 in the DOM.
Similarly, if I close that, it goes from block to none.

After that, I now have 2 dialogs in the DOM with ```display: none```.

If I keep calling the ```showDialog()``` function and closing the dialog, I end up with further ones in the DOM.

Strangely, if I pass in an ID other than 'null', such as 'myDialog', the newly created dialog doesn't have that id set on it, it has a random one.

**Comment by keejelo** [comment] 2021-03-31 05:32
ok, I'll test it and try to see if I can reproduce the same result on my end.
<strike>..just a quick thought: have you tried using <code>let modal</code> instead of <code>const modal</code> ?
any difference ?</strike>

**Comment by keejelo** [comment] 2021-03-31 13:58
Tested the example you wrote, but I got error message "unexpected token >." , in my javascript-editor regarding the code: 
<code>( returnCode, inputValue ) => { }</code>

..but it still worked, the box displayed and was deleted on closing, so I dont know if it has someting to do with that errormessage I got ?   (or if that was just because I hadnt defined it or something, probably. There was no error in browser).

<pre>
function showDialog()
{
    var html = '&lt;p&gt;hello&lt;/p&gt;';
    const modal = EasyDialogBox.create(null, "dlg", "Test Dialog", html, ( returnCode, inputValue ) => { });
    modal.onClose = function() { modal.destroy(); /* Other stuff in here too */ };
    modal.show();
};
</pre>

Edit:
So I was not able to recreate the issue with that quick test.

But I've experienced what you talk about if I create 2 boxes with the same object name without any 'id' and without deleting the first one, I can recall something similar, then the reference to the first box and DOM element is overwritten and lost, and it cannot be deleted with the destroy func, but in the example you give this seems not to be the case.. it worked fine for me.

If you give it an id it should be using that each time when showing, if not destroying it first, it should not create a new DOM element since it already has an existing one with its id to use. But using null instead of an id should not be any problem as long as you have the object name, it still should be able to destroy it like in the example.

<br>
btw.: regarding the random id: they occur when not setting an id when creating, so the function creates a random id and uses that for internally reference to the dialog box object, the internal funcs use it

**Comment by ray73864** [comment] 2021-03-31 19:31
So very weird.

It's started working properly now.

The ```( returnCode, inputValue ) => {}``` is just an inline callback function, the callback does nothing, it's just something I keep adding in.

Upon removing it though, maybe that's what fixed it, not sure.

I'll keep testing to see what happens.

**Comment by keejelo** [comment] 2021-04-01 06:28
Ok, strange, but good to hear that it's working properly now.
Yes keep testing if you can, and keep me posted. [thumbsUp]

(btw.: the callback is optional so you can just use <code>0</code> (zero) or <code>null</code> instead if not using it, or use a shorter syntax <br /><code>EasyDialogBox.create(id, strBoxTypeClass, strTitle, strMessage);</code>
but I'm sure you know that already)

**Comment by keejelo** [comment] 2021-04-01 09:08
Found a bug that may have cause the strange behaviour that you experienced.
Updated the file "easydlg.js" in the repo, try it, think maybe I fixed it (?)

--> There was a bug when creating dialog without 'id', the random generated id sometimes was created with a number as the first character, causing error when selecting elements in the internal functions.

Now fixed by always adding the letter 'a' in front of the random generated id string.
I found this by accident when I was "brute forcing" dailogbox creation, spamming the function.
Guess it makes sence since JS/CSS dont like selectors, id and class names starting with a number character, even though some documentation here and there say it's no problem.

**Closed as completed** 2021-07-18 11:24 UTC
